package com.hotel.service;

import com.hotel.entity.*;
import com.hotel.interfaces.*;
import com.hotel.ultis.Constants;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ManagerServiceTest {
    private IRoomTypeRepository types;private IRoomRepository rooms;private IRoomRateRepository rates;private IHousekeepingRepository housekeeping;private IMaintenanceRepository maintenance;private IManagementRepository management;private IUserRepository users;private ManagerService service;
    @BeforeEach void setUp(){types=mock(IRoomTypeRepository.class);rooms=mock(IRoomRepository.class);rates=mock(IRoomRateRepository.class);housekeeping=mock(IHousekeepingRepository.class);maintenance=mock(IMaintenanceRepository.class);management=mock(IManagementRepository.class);users=mock(IUserRepository.class);service=new ManagerService(types,rooms,rates,housekeeping,maintenance,management,users);}
    @Test void roomTypeCrudActivationAndAmenityAssociation(){RoomType t=type();when(types.findById(1)).thenReturn(t);service.createRoomType(t);verify(types).insert(t);service.setRoomTypeActive(1,false);verify(types).setActive(1,false);t.setAmenitiesJson("[\"WiFi\"]");service.addAmenity(1,"TV");verify(types).updateAmenities(1,"[\"WiFi\",\"TV\"]");service.removeAmenity(1,0);verify(types).updateAmenities(1,"[]");}
    @Test void roomImagesCanAddUpdateReorderAndRemove(){RoomType t=type();t.setImagesJson("[\"https://a.test/1.jpg\",\"https://a.test/2.png\"]");when(types.findById(1)).thenReturn(t);service.addImage(1,"https://a.test/3.webp");verify(types).updateImages(1,"[\"https://a.test/1.jpg\",\"https://a.test/2.png\",\"https://a.test/3.webp\"]");service.updateImage(1,0,"https://a.test/new.jpg");verify(types).updateImages(1,"[\"https://a.test/new.jpg\",\"https://a.test/2.png\"]");service.moveImage(1,1,-1);verify(types).updateImages(1,"[\"https://a.test/2.png\",\"https://a.test/1.jpg\"]");service.removeImage(1,1);verify(types).updateImages(1,"[\"https://a.test/1.jpg\"]");}
    @Test void physicalRoomCreateUpdateAndOccupiedTransitionGuard(){RoomType t=type();when(types.findById(1)).thenReturn(t);Room room=new Room();room.setRoomTypeId(1);room.setRoomNumber("201");service.createRoom(room);assertEquals(Constants.CLEAN_DIRTY,room.getCleaningStatus());verify(rooms).insert(room);Room occupied=new Room();occupied.setRoomId(9);occupied.setOperationalStatus(Constants.ROOM_OCCUPIED);when(rooms.findById(9)).thenReturn(occupied);assertThrows(IllegalStateException.class,()->service.changeOperationalStatus(9,Constants.ROOM_BLOCKED));verify(rooms,never()).updateOperationalStatus(anyLong(),anyString(),anyBoolean());}
    @Test void invalidPricingDoesNotPartiallyUpdateBasePrice(){when(types.findById(1)).thenReturn(type());LocalDate future=LocalDate.now().plusDays(2);assertThrows(IllegalArgumentException.class,()->service.updatePricing(1,new BigDecimal("100"),future,future.minusDays(1),new BigDecimal("120"),false));verifyNoInteractions(rates);service.updatePricing(1,new BigDecimal("100"),future,future.plusDays(2),new BigDecimal("120"),true);verify(rates).updatePricing(1,new BigDecimal("100"),future,future.plusDays(2),new BigDecimal("120"),true);}
    @Test void housekeepingCreateAssignMonitorAndInspection(){Room room=new Room();room.setRoomId(3);room.setOperationalStatus(Constants.ROOM_AVAILABLE);when(rooms.findById(3)).thenReturn(room);when(housekeeping.hasActiveTask(3)).thenReturn(false);User staff=staff();when(users.findById(8)).thenReturn(staff);when(housekeeping.findById(4)).thenReturn(new HousekeepingTask());service.createHousekeepingTask(3,null,8L,"CHECKOUT_CLEANING","HIGH",null,"note",2);verify(housekeeping).insert(any(HousekeepingTask.class));service.assignHousekeeping(4,8);verify(housekeeping).assign(4,8);assertThrows(IllegalArgumentException.class,()->service.inspectHousekeeping(4,8,false,""));service.inspectHousekeeping(4,8,true,"ok");verify(housekeeping).inspect(eq(4L),eq(8L),eq(true),eq("ok"),startsWith("MT"));}
    @Test void duplicateHousekeepingTaskIsRejected(){Room room=new Room();room.setRoomId(3);room.setOperationalStatus(Constants.ROOM_AVAILABLE);when(rooms.findById(3)).thenReturn(room);when(housekeeping.hasActiveTask(3)).thenReturn(true);assertThrows(IllegalStateException.class,()->service.createHousekeepingTask(3,null,null,"CHECKOUT_CLEANING","NORMAL",null,null,2));verify(housekeeping,never()).insert(any());}
    @Test void maintenancePriorityAssignmentProgressResolveReopenAndClose(){MaintenanceTicket issue=new MaintenanceTicket();when(maintenance.findById(5)).thenReturn(issue);when(users.findById(8)).thenReturn(staff());service.assignMaintenance(5,"URGENT",8);service.startMaintenance(5,8);service.resolveMaintenance(5,8,"fixed");service.reopenMaintenance(5,8L);service.closeMaintenance(5);verify(maintenance).assign(5,"URGENT",8);verify(maintenance).start(5,8);verify(maintenance).resolve(5,8,"fixed");verify(maintenance).reopen(5,8L);verify(maintenance).close(5);}
    @Test void dashboardAndReportUseRepositoryAndValidateDates(){ManagerDashboard dashboard=new ManagerDashboard();when(management.loadDashboard(any())).thenReturn(dashboard);assertSame(dashboard,service.getDashboard(null));assertThrows(IllegalArgumentException.class,()->service.getReport(LocalDate.now(),LocalDate.now().minusDays(1)));ManagementReport report=new ManagementReport();when(management.loadReport(any(),any())).thenReturn(report);assertSame(report,service.getReport(LocalDate.now().minusDays(1),LocalDate.now()));}
    private RoomType type(){RoomType t=new RoomType();t.setRoomTypeId(1);t.setTypeCode("DLX");t.setTypeName("Deluxe");t.setMaxAdults(2);t.setMaxChildren(1);t.setBasePrice(new BigDecimal("100"));t.setAmenitiesJson("[]");t.setImagesJson("[]");t.setActive(true);return t;}
    private User staff(){User u=new User();u.setUserId(8);u.setRoleCode(Constants.ROLE_SERVICE_STAFF);u.setStatusCode("ACTIVE");return u;}
}
