<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="_header.jspf" %>
<div class="page-head"><div><h1>Housekeeping Tasks</h1><div class="muted">${isManager ? 'Manager: tạo, phân công và theo dõi' : 'Service Staff: thực hiện cleaning và inspection'}</div></div><c:if test="${isManager}"><a class="btn" href="${pageContext.request.contextPath}/manager/dashboard">Dashboard</a></c:if></div>
<c:if test="${isManager}"><div class="card"><h2>Tạo housekeeping task</h2><form method="post" class="form-grid"><input type="hidden" name="action" value="create">
  <div><label>Phòng *</label><select name="roomId" required style="width:100%"><c:forEach var="r" items="${rooms}"><option value="${r.roomId}"><c:out value="${r.roomNumber}"/> · ${r.operationalStatus} · ${r.cleaningStatus}</option></c:forEach></select></div>
  <div><label>Nhân viên</label><select name="staffId" style="width:100%"><option value="">Chưa phân công</option><c:forEach var="u" items="${staff}"><option value="${u.userId}"><c:out value="${u.fullName}"/></option></c:forEach></select></div>
  <div><label>Task type *</label><select name="taskType" required style="width:100%"><option>CHECKOUT_CLEANING</option><option>STAYOVER_CLEANING</option><option>DEEP_CLEANING</option></select></div>
  <div><label>Priority *</label><select name="priority" required style="width:100%"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select></div>
  <div><label>Scheduled at</label><input type="datetime-local" name="scheduledAt" style="width:100%"></div><div><label>Reservation ID (nếu có)</label><input type="number" min="1" name="reservationId" style="width:100%"></div>
  <div class="full"><label>Ghi chú</label><textarea name="notes" maxlength="500" rows="3" style="width:100%"></textarea></div><div class="full"><button class="btn" type="submit">Tạo task</button></div>
</form></div></c:if>
<div class="card table-wrap"><h2>${isManager ? 'Theo dõi tiến độ' : 'Công việc của tôi'}</h2>
<c:choose><c:when test="${empty tasks}"><div class="empty">Không có housekeeping task.</div></c:when><c:otherwise><table><thead><tr><th>ID</th><th>Phòng</th><th>Loại / ưu tiên</th><th>Nhân viên</th><th>Trạng thái</th><th>Cleaning / inspection</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach var="t" items="${tasks}"><tr><td>#${t.housekeepingTaskId}</td><td><b><c:out value="${t.roomNumber}"/></b></td><td>${t.taskType}<br><span class="badge">${t.priorityCode}</span></td><td><c:out value="${empty t.staffName ? 'Chưa phân công' : t.staffName}"/></td><td><span class="badge status-${t.statusCode}">${t.statusCode}</span></td><td><c:if test="${not empty t.completedAt}">Cleaning xong<br></c:if><c:if test="${not empty t.inspectionStatus}"><span class="badge status-${t.inspectionStatus}">${t.inspectionStatus}</span></c:if></td><td>
  <c:choose><c:when test="${isManager && (t.statusCode == 'PENDING' || t.statusCode == 'ASSIGNED' || t.statusCode == 'IN_PROGRESS')}"><form method="post" class="inline"><input type="hidden" name="action" value="assign"><input type="hidden" name="taskId" value="${t.housekeepingTaskId}"><select name="staffId" required><c:forEach var="u" items="${staff}"><option value="${u.userId}" ${t.assignedStaffUserId == u.userId ? 'selected' : ''}><c:out value="${u.fullName}"/></option></c:forEach></select><button class="btn btn-small">${empty t.assignedStaffUserId ? 'Giao việc' : 'Reassign'}</button></form></c:when>
  <c:when test="${!isManager && t.statusCode == 'ASSIGNED'}"><form method="post"><input type="hidden" name="action" value="start"><input type="hidden" name="taskId" value="${t.housekeepingTaskId}"><button class="btn btn-small">Bắt đầu</button></form></c:when>
  <c:when test="${!isManager && t.statusCode == 'IN_PROGRESS' && empty t.completedAt}"><form method="post"><input type="hidden" name="action" value="complete"><input type="hidden" name="taskId" value="${t.housekeepingTaskId}"><input name="notes" maxlength="500" placeholder="Cleaning notes"><button class="btn btn-success btn-small">Hoàn tất cleaning</button></form></c:when>
  <c:when test="${!isManager && t.statusCode == 'IN_PROGRESS' && not empty t.completedAt}"><form method="post"><input type="hidden" name="taskId" value="${t.housekeepingTaskId}"><textarea name="notes" maxlength="500" placeholder="Inspection notes"></textarea><div><button class="btn btn-success btn-small" name="action" value="inspectPass">Inspection PASS</button><button class="btn btn-danger btn-small" name="action" value="inspectFail">FAIL + tạo maintenance</button></div></form></c:when>
  <c:otherwise><span class="muted">—</span></c:otherwise></c:choose>
</td></tr></c:forEach></tbody></table></c:otherwise></c:choose>
</div>
<%@ include file="_footer.jspf" %>
