<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="_header.jspf" %>
<div class="page-head"><div><h1>Maintenance Issues</h1><div class="muted">${isManager ? 'Manager: ưu tiên, phân công, review và đóng issue' : 'Service Staff: báo cáo, sửa chữa và ghi kết quả'}</div></div><c:if test="${isManager}"><a class="btn" href="${pageContext.request.contextPath}/manager/dashboard">Dashboard</a></c:if></div>
<c:if test="${!isManager}"><div class="card"><h2>Báo maintenance issue</h2><form method="post" class="form-grid"><input type="hidden" name="action" value="report"><div><label>Phòng *</label><select name="roomId" required style="width:100%"><c:forEach var="r" items="${rooms}"><option value="${r.roomId}"><c:out value="${r.roomNumber}"/></option></c:forEach></select></div><div><label>Priority</label><select name="priority" style="width:100%"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select></div><div class="full"><label>Tiêu đề *</label><input name="title" required maxlength="150" style="width:100%"></div><div class="full"><label>Mô tả *</label><textarea name="description" required rows="4" style="width:100%"></textarea></div><div class="full"><button class="btn">Báo issue</button></div></form></div></c:if>
<div class="card"><form method="get" class="inline"><select name="status"><option value="">Tất cả trạng thái</option><c:forEach var="s" items="OPEN,ASSIGNED,IN_PROGRESS,RESOLVED,CLOSED,CANCELLED"><option ${param.status == s ? 'selected' : ''}>${s}</option></c:forEach></select><select name="priority"><option value="">Tất cả ưu tiên</option><c:forEach var="p" items="LOW,NORMAL,HIGH,URGENT"><option ${param.priority == p ? 'selected' : ''}>${p}</option></c:forEach></select><button class="btn">Lọc</button></form></div>
<div class="card table-wrap"><c:choose><c:when test="${empty issues}"><div class="empty">Không có maintenance issue.</div></c:when><c:otherwise><table><thead><tr><th>Mã</th><th>Phòng</th><th>Issue</th><th>Priority</th><th>Assignee</th><th>Status</th><th>Kết quả</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach var="i" items="${issues}"><tr><td><c:out value="${i.ticketCode}"/></td><td><b><c:out value="${i.roomNumber}"/></b></td><td><b><c:out value="${i.title}"/></b><br><span class="muted"><c:out value="${i.description}"/></span></td><td>${i.priorityCode}</td><td><c:out value="${empty i.staffName ? 'Chưa giao' : i.staffName}"/></td><td><span class="badge status-${i.statusCode}">${i.statusCode}</span></td><td><c:out value="${i.resolutionNote}"/></td><td>
<c:choose><c:when test="${isManager && i.statusCode != 'CLOSED' && i.statusCode != 'CANCELLED'}"><form method="post" class="inline"><input type="hidden" name="action" value="assign"><input type="hidden" name="ticketId" value="${i.maintenanceTicketId}"><select name="priority"><option ${i.priorityCode == 'LOW' ? 'selected' : ''}>LOW</option><option ${i.priorityCode == 'NORMAL' ? 'selected' : ''}>NORMAL</option><option ${i.priorityCode == 'HIGH' ? 'selected' : ''}>HIGH</option><option ${i.priorityCode == 'URGENT' ? 'selected' : ''}>URGENT</option></select><select name="staffId" required><c:forEach var="u" items="${staff}"><option value="${u.userId}" ${i.assignedStaffUserId == u.userId ? 'selected' : ''}><c:out value="${u.fullName}"/></option></c:forEach></select><button class="btn btn-small">Assign / Reassign</button></form><c:if test="${i.statusCode == 'RESOLVED'}"><form method="post" class="inline"><input type="hidden" name="action" value="close"><input type="hidden" name="ticketId" value="${i.maintenanceTicketId}"><button class="btn btn-success btn-small">Xác nhận đóng</button></form></c:if></c:when>
<c:when test="${isManager && i.statusCode == 'CLOSED'}"><form method="post" class="inline"><input type="hidden" name="action" value="reopen"><input type="hidden" name="ticketId" value="${i.maintenanceTicketId}"><select name="staffId"><option value="">Chưa giao</option><c:forEach var="u" items="${staff}"><option value="${u.userId}"><c:out value="${u.fullName}"/></option></c:forEach></select><button class="btn btn-danger btn-small">Reopen</button></form></c:when>
<c:when test="${!isManager && i.assignedStaffUserId == sessionScope.currentUser.userId && i.statusCode == 'ASSIGNED'}"><form method="post"><input type="hidden" name="action" value="start"><input type="hidden" name="ticketId" value="${i.maintenanceTicketId}"><button class="btn btn-small">Bắt đầu sửa</button></form></c:when>
<c:when test="${!isManager && i.assignedStaffUserId == sessionScope.currentUser.userId && i.statusCode == 'IN_PROGRESS'}"><form method="post"><input type="hidden" name="action" value="resolve"><input type="hidden" name="ticketId" value="${i.maintenanceTicketId}"><textarea name="resolutionNote" required maxlength="500" placeholder="Repair notes"></textarea><button class="btn btn-success btn-small">Gửi kết quả RESOLVED</button></form></c:when><c:otherwise>—</c:otherwise></c:choose>
</td></tr></c:forEach></tbody></table></c:otherwise></c:choose></div>
<%@ include file="_footer.jspf" %>
